# Generated by Django 2.0.3 on 2018-03-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('project_manager', models.CharField(max_length=255)),
                ('status', models.SmallIntegerField(choices=[(1, 'Не начато'), (2, 'В работе'), (3, 'Отстает'), (4, 'Выполнено'), (5, 'Приостановлено')])),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wbs_code', models.CharField(max_length=32, unique=True)),
                ('task_type', models.SmallIntegerField(choices=[(1, 'Задача'), (2, 'Веха')], default=1)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('predecessor', models.IntegerField(blank=True, null=True)),
                ('responsible', models.CharField(max_length=255)),
                ('status', models.SmallIntegerField(choices=[(1, 'Не начато'), (2, 'В работе'), (3, 'Отстает'), (4, 'Выполнено'), (5, 'Приостановлено')])),
                ('project', models.ForeignKey(blank=True, null=True, on_delete='PROTECT', to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('project_role', models.SmallIntegerField(choices=[(1, 'Участник'), (2, 'Менеджер'), (3, 'Стейкхолдер')])),
                ('occupation', models.CharField(max_length=250)),
                ('other', models.CharField(max_length=250)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete='PROTECT', to='project.Project')),
            ],
        ),
    ]
