# Generated by Django 2.0.3 on 2018-03-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='successor',
            field=models.ManyToManyField(blank=True, null=True, related_name='_task_successor_+', to='project.Task'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='predecessor',
        ),
        migrations.AddField(
            model_name='task',
            name='predecessor',
            field=models.ManyToManyField(blank=True, null=True, related_name='_task_predecessor_+', to='project.Task'),
        ),
    ]
