# Generated by Django 2.0.3 on 2018-03-13 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_m',
            new_name='project_manager',
        ),
    ]
