# Generated by Django 2.0.3 on 2018-04-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180331_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='predecessor',
        ),
        migrations.RemoveField(
            model_name='task',
            name='successor',
        ),
        migrations.AddField(
            model_name='relation',
            name='task',
            field=models.OneToOneField(on_delete='PROTECT', to='project.Task'),
        ),
    ]
