# Generated by Django 2.0.3 on 2018-04-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180419_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='percent_complete',
            field=models.PositiveIntegerField(max_length=3),
        ),
    ]
