# Generated by Django 2.0.3 on 2018-04-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180422_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete='PROTECT', to='project.User'),
        ),
    ]
