# Generated by Django 2.0.3 on 2018-04-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180401_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='predecessor',
            field=models.ManyToManyField(related_name='_task_predecessor_+', to='project.Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='successor',
            field=models.ManyToManyField(related_name='_task_successor_+', to='project.Task'),
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
    ]
