# Generated by Django 2.0.3 on 2018-04-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180419_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='percent_complete',
            field=models.SmallIntegerField(default=0),
        ),
    ]
