# Generated by Django 2.0.3 on 2018-04-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20180419_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='percent_complete',
            field=models.BigIntegerField(default=0),
        ),
    ]
