# Generated by Django 2.0.3 on 2018-04-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20180401_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='predecessor',
            field=models.ManyToManyField(blank=True, related_name='_task_predecessor_+', to='project.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='successor',
            field=models.ManyToManyField(blank=True, related_name='_task_successor_+', to='project.Task'),
        ),
    ]
