# Generated by Django 2.0.3 on 2018-04-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20180422_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to='project.Project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to='project.User'),
        ),
    ]
