# Generated by Django 2.0.3 on 2018-03-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20180318_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[(1, 'Не начато'), (2, 'В работе'), (3, 'Отстает'), (4, 'Выполнено')], max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(1, 'Не начато'), (2, 'В работе'), (3, 'Отстает'), (4, 'Выполнено')], max_length=64),
        ),
    ]
