# Generated by Django 2.0.3 on 2018-04-01 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20180401_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='successor',
        ),
    ]
