# Generated by Django 2.0.3 on 2018-03-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20180318_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Не начато'), (2, 'В работе'), (3, 'Отстает'), (4, 'Выполнено')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Не начато'), (2, 'В работе'), (3, 'Отстает'), (4, 'Выполнено')]),
        ),
    ]
