# Generated by Django 2.0.3 on 2018-04-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_task_successor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='predecessor',
        ),
        migrations.AddField(
            model_name='task',
            name='predecessor',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to='project.Task'),
        ),
    ]
