# Generated by Django 2.0.3 on 2018-03-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20180318_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
