# Generated by Django 2.0.3 on 2018-04-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20180401_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='predecessor',
        ),
        migrations.AddField(
            model_name='task',
            name='predecessors',
            field=models.ForeignKey(blank=True, null=True, on_delete='PROTECT', to='project.Task'),
        ),
    ]
