# Generated by Django 2.0.3 on 2018-03-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_user'),
        ('project', '0010_auto_20180320_1946'),
    ]

    operations = [
    ]
