# Generated by Django 2.0.3 on 2018-04-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20180401_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='predecessors',
        ),
        migrations.AddField(
            model_name='task',
            name='predecessors',
            field=models.ForeignKey(blank=True, null=True, on_delete='PROTECT', to='project.Task'),
        ),
    ]
