# Generated by Django 2.0.3 on 2018-04-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20180401_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='predecessors',
        ),
        migrations.AddField(
            model_name='task',
            name='predecessors',
            field=models.ManyToManyField(blank=True, related_name='_task_predecessors_+', to='project.Task'),
        ),
    ]
