# Generated by Django 2.0.3 on 2018-04-01 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20180401_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='predecessors',
        ),
    ]
