# Generated by Django 2.0.3 on 2018-04-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_task_predecessors'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='predecessors',
        ),
        migrations.AddField(
            model_name='taskrel',
            name='predecessors',
            field=models.ForeignKey(on_delete='PROTECT', to='project.Task'),
        ),
    ]
