# Generated by Django 2.0.3 on 2018-04-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20180401_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrel',
            name='successor',
            field=models.ForeignKey(blank=True, null=True, on_delete='PROTECT', related_name='+', to='project.Task'),
        ),
        migrations.AlterField(
            model_name='taskrel',
            name='predecessors',
            field=models.OneToOneField(blank=True, null=True, on_delete='PROTECT', to='project.Task'),
        ),
    ]
