# Generated by Django 2.0.3 on 2018-04-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20180401_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrel',
            name='predecessors',
            field=models.ForeignKey(blank=True, null=True, on_delete='PROTECT', to='project.Task'),
        ),
    ]
