# Generated by Django 2.0.3 on 2018-04-21 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_auto_20180413_2257'),
    ]

    operations = [
    ]
