# Generated by Django 2.0.3 on 2018-04-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_merge_20180421_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskrel',
            name='predecessors',
            field=models.ForeignKey(blank=True, null=True, on_delete='PROTECT', to='project.Task'),
        ),
        migrations.AddField(
            model_name='taskrel',
            name='successor',
            field=models.ForeignKey(blank=True, null=True, on_delete='PROTECT', related_name='+', to='project.Task'),
        ),
    ]
