# Generated by Django 2.0.3 on 2018-04-21 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20180419_2237'),
        ('project', '0022_auto_20180421_1124'),
    ]

    operations = [
    ]
